#AutoConfigurationReportLoggingInitializer
debug: false

spring:
  application:
    name: x-alert-one
  main:
    banner-mode: "off"
  profiles:
    active: default


server:
  port: 8080

#xwatcher.options
xwatcher:
  config:
    watcherDir: "E:\\watchers"

